apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - rbac-argocd-rollouts-git-updater.yaml
  - deployment-argocd-rollouts-git-updater.yaml

images:
  - name: argocd-rollouts-git-updater
    newName: myorg/argocd-rollouts-git-updater
    newTag: v0.1
