---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-rollouts-git-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-apps-viewer
rules:
- apiGroups: ["argoproj.io"]
  resources: ["applications"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-apps-viewer-argocd-rollouts-git-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-apps-viewer
subjects:
  - kind: ServiceAccount
    name: argocd-rollouts-git-updater
    namespace: argocd
