#!/bin/bash

# This produces a semver compatible pre-release version number from "git
# describe" output.

GIT_DESCRIBE=$(git describe --tags || (git tag -a v0.0.0 -m "tag v0.0.0"; git describe --tags))

GIT_COMMITS=$(echo "${GIT_DESCRIBE}" | awk -F - '{ print $2 }')
GIT_SHA=$(echo "${GIT_DESCRIBE}" | awk -F - '{ print $3 }' )
GIT_TAG=$(echo "${GIT_DESCRIBE}" | awk -F - '{ print $1 }')

ARTIFACT_VERSION="${GIT_TAG}"
if [ ! -z ${GIT_COMMITS+x} ]; then
  ARTIFACT_VERSION="${ARTIFACT_VERSION}-${GIT_COMMITS}.${GIT_SHA}"
fi

